#!/bin/bash

usage()
{
    echo "julia2prv"
    echo "Wrapper to the mpi2prv tool to convert Extrae for Julia mpits to a paraver trace"
    echo 
    echo "Usage: julia2prv TRACENAME JULIATRACE [JULIATRACE...]"
    echo "Creates a trace with name TRACENAME by combining mpits in JULIATRACE files"
    echo

}

# check whether user had supplied -h or --help . If yes display usage
if [[ ( $@ == "--help") ||  $@ == "-h" ]]
then 
	usage
	exit 0
fi

# if less than two arguments supplied, display usage 
	if [  $# -le 1 ] 
	then 
		usage
		exit 1
	fi 

TRACE=$(mktemp -p .)

trace_name=$1
shift

cat ${@} > ${TRACE} 
mpi2prv -v -f ${TRACE} -o ${trace_name}
rm $TRACE

